stages:
  - trigger

trigger-backend:
  stage: trigger
  rules:
    - changes:
        - backend/**/*   # если изменился backend
  trigger:
    include: backend/.gitlab-ci.yml
    strategy: depend

#trigger-frontend:
#  stage: trigger
#  rules:
#    - changes:
#        - frontend/**/*   # если изменился frontend
#  trigger:
#    include: frontend/.gitlab-ci.yml
#    strategy: depend
