stages:
  - build
  - test
  - deploy

build-backend:
  stage: build
  image: docker:cli
  services:
    - name: docker:dind
      alias: docker
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  tags:
    - docker
  script:
    - docker version
    - docker build -t my-app .

test-backend-flake8:
  stage: test
  tags:
    - docker
  script:
    - flake8 .
  needs:
    - build-backend

deploy-backend:
  stage: deploy  
  tags:
    - docker
  script:
    - echo "Deploy"
  needs:
    - job: test-backend-flake8